---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - _misc/*
    - bin/*
    - vendor/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*

RSpec/ExampleLength:
  Max: 10

RSpec/VerifiedDoubleReference:
  Enabled: false

Style/GuardClause:
  Enabled: false
